//! Provenance metadata for generated code
//!
//! Tracks the origin, generation context, and verification status of generated code

pub mod metadata;
pub mod extraction;
pub mod embedding;

pub use metadata::{ProvenanceMetadata, GenerationContext, VerificationStatus};
pub use extraction::extract_provenance;
pub use embedding::embed_provenance;

use crate::error::{CompileError, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Provenance tracking system
pub struct ProvenanceTracker {
    metadata_store: HashMap<String, ProvenanceMetadata>,
    enabled: bool,
}

impl ProvenanceTracker {
    /// Create a new provenance tracker
    pub fn new() -> Self {
        Self {
            metadata_store: HashMap::new(),
            enabled: true,
        }
    }

    /// Enable provenance tracking
    pub fn enable(&mut self) {
        self.enabled = true;
    }

    /// Disable provenance tracking
    pub fn disable(&mut self) {
        self.enabled = false;
    }

    /// Check if provenance tracking is enabled
    pub fn is_enabled(&self) -> bool {
        self.enabled
    }

    /// Store metadata for a definition
    pub fn store(&mut self, definition_name: String, metadata: ProvenanceMetadata) {
        if self.enabled {
            self.metadata_store.insert(definition_name, metadata);
        }
    }

    /// Retrieve metadata for a definition
    pub fn retrieve(&self, definition_name: &str) -> Option<&ProvenanceMetadata> {
        self.metadata_store.get(definition_name)
    }

    /// Get all stored metadata
    pub fn all_metadata(&self) -> &HashMap<String, ProvenanceMetadata> {
        &self.metadata_store
    }

    /// Export metadata to JSON
    pub fn export_json(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(&self.metadata_store)
    }

    /// Import metadata from JSON
    pub fn import_json(&mut self, json: &str) -> serde_json::Result<()> {
        let metadata: HashMap<String, ProvenanceMetadata> = serde_json::from_str(json)?;
        self.metadata_store.extend(metadata);
        Ok(())
    }

    /// Clear all metadata
    pub fn clear(&mut self) {
        self.metadata_store.clear();
    }
}

impl Default for ProvenanceTracker {
    fn default() -> Self {
        Self::new()
    }
}

/// Provenance query interface
pub struct ProvenanceQuery<'a> {
    tracker: &'a ProvenanceTracker,
}

impl<'a> ProvenanceQuery<'a> {
    /// Create a new query interface
    pub fn new(tracker: &'a ProvenanceTracker) -> Self {
        Self { tracker }
    }

    /// Find all metadata generated by a specific agent
    pub fn by_agent(&self, agent: &str) -> Vec<(&String, &ProvenanceMetadata)> {
        self.tracker
            .metadata_store
            .iter()
            .filter(|(_, meta)| meta.generated_by == agent)
            .collect()
    }

    /// Find all metadata using a specific pattern
    pub fn by_pattern(&self, pattern_id: &str) -> Vec<(&String, &ProvenanceMetadata)> {
        self.tracker
            .metadata_store
            .iter()
            .filter(|(_, meta)| meta.pattern_id.as_deref() == Some(pattern_id))
            .collect()
    }

    /// Find all verified metadata
    pub fn verified(&self) -> Vec<(&String, &ProvenanceMetadata)> {
        self.tracker
            .metadata_store
            .iter()
            .filter(|(_, meta)| meta.verification.is_verified())
            .collect()
    }

    /// Find all unverified metadata
    pub fn unverified(&self) -> Vec<(&String, &ProvenanceMetadata)> {
        self.tracker
            .metadata_store
            .iter()
            .filter(|(_, meta)| !meta.verification.is_verified())
            .collect()
    }

    /// Find all metadata with test failures
    pub fn with_failures(&self) -> Vec<(&String, &ProvenanceMetadata)> {
        self.tracker
            .metadata_store
            .iter()
            .filter(|(_, meta)| meta.verification.has_failures())
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provenance::metadata::{ProvenanceMetadata, VerificationStatus};

    #[test]
    fn test_provenance_tracker_creation() {
        let tracker = ProvenanceTracker::new();
        assert!(tracker.is_enabled());
        assert_eq!(tracker.metadata_store.len(), 0);
    }

    #[test]
    fn test_provenance_tracker_store_retrieve() {
        let mut tracker = ProvenanceTracker::new();
        let metadata = ProvenanceMetadata::new("claude-sonnet-4".to_string());

        tracker.store("square".to_string(), metadata);
        assert!(tracker.retrieve("square").is_some());
        assert!(tracker.retrieve("nonexistent").is_none());
    }

    #[test]
    fn test_provenance_tracker_disable() {
        let mut tracker = ProvenanceTracker::new();
        tracker.disable();
        assert!(!tracker.is_enabled());

        let metadata = ProvenanceMetadata::new("claude-sonnet-4".to_string());
        tracker.store("square".to_string(), metadata);
        assert_eq!(tracker.metadata_store.len(), 0); // Should not store when disabled
    }

    #[test]
    fn test_provenance_query_by_agent() {
        let mut tracker = ProvenanceTracker::new();
        let metadata1 = ProvenanceMetadata::new("claude-sonnet-4".to_string());
        let metadata2 = ProvenanceMetadata::new("other-agent".to_string());

        tracker.store("word1".to_string(), metadata1);
        tracker.store("word2".to_string(), metadata2);

        let query = ProvenanceQuery::new(&tracker);
        let results = query.by_agent("claude-sonnet-4");
        assert_eq!(results.len(), 1);
    }
}
