\ fifth/examples/config-generator/main.fs
\ Configuration file generator

require ~/.fifth/lib/core.fs

\ Configuration
: output-dir ( -- addr u ) s" output/" ;

variable config-fid

: config>file ( filename-addr filename-u -- )
  w/o create-file throw config-fid ! ;

: config-emit ( addr u -- )
  config-fid @ write-file throw ;

: config-nl ( -- )
  s\" \n" config-emit ;

: config-line ( addr u -- )
  config-emit config-nl ;

: config-close ( -- )
  config-fid @ close-file throw ;

\ --- Nginx Configuration ---

: nginx-header ( -- )
  s" # Generated by Fifth config-generator" config-line
  s" # Do not edit manually" config-line
  config-nl ;

: nginx-upstream ( name-addr name-u port -- )
  s" upstream " config-emit
  2swap config-emit
  s"  {" config-line
  s"     server 127.0.0.1:" config-emit
  0 <# #s #> config-emit
  s" ;" config-line
  s" }" config-line
  config-nl ;

: nginx-location ( path-addr path-u -- )
  s"     location " config-emit
  config-emit
  s"  {" config-line ;

: nginx-location-end ( -- )
  s"     }" config-line ;

: nginx-proxy-pass ( upstream-addr upstream-u -- )
  s"         proxy_pass http://" config-emit
  config-emit
  s" ;" config-line ;

: nginx-server ( port -- )
  s" server {" config-line
  s"     listen " config-emit
  0 <# #s #> config-emit
  s" ;" config-line
  s"     server_name localhost;" config-line
  config-nl ;

: nginx-server-end ( -- )
  s" }" config-line ;

: generate-nginx ( -- )
  s" output/nginx.conf" config>file
  nginx-header

  s" app" 3000 nginx-upstream

  80 nginx-server
  s" /" nginx-location
  s" app" nginx-proxy-pass
  nginx-location-end
  nginx-server-end

  config-close
  s" Generated: output/nginx.conf" type cr ;

\ --- Systemd Configuration ---

: systemd-header ( -- )
  s" # Generated by Fifth config-generator" config-line ;

: systemd-unit ( desc-addr desc-u -- )
  s" [Unit]" config-line
  s" Description=" config-emit config-line
  s" After=network.target" config-line
  config-nl ;

: systemd-service ( cmd-addr cmd-u user-addr user-u -- )
  s" [Service]" config-line
  s" Type=simple" config-line
  s" User=" config-emit config-line
  s" ExecStart=" config-emit config-line
  s" Restart=always" config-line
  s" RestartSec=5" config-line
  config-nl ;

: systemd-install ( -- )
  s" [Install]" config-line
  s" WantedBy=multi-user.target" config-line ;

: generate-systemd ( name-addr name-u -- )
  str-reset
  s" output/" str+
  2dup str+
  s" .service" str+
  str$ config>file

  systemd-header
  s" My Application Service" systemd-unit
  s" /usr/local/bin/myapp" s" www-data" systemd-service
  systemd-install

  config-close
  s" Generated: output/" type type s" .service" type cr ;

\ --- Main ---

: ensure-output ( -- )
  s" mkdir -p output" system drop ;

: usage ( -- )
  s" Configuration Generator" type cr
  s" " type cr
  s" Usage:" type cr
  s"   ./fifth config-generator/main.fs nginx" type cr
  s"   ./fifth config-generator/main.fs systemd <name>" type cr ;

: main ( -- )
  ensure-output
  argc @ 2 < if
    usage exit
  then
  1 argv
  2dup s" nginx" compare 0= if 2drop generate-nginx exit then
  2dup s" systemd" compare 0= if
    2drop
    argc @ 3 < if
      s" myapp" generate-systemd
    else
      2 argv generate-systemd
    then
    exit
  then
  2drop usage ;

main
bye
