\ fifth/examples/project-scaffolder/main.fs
\ Project scaffolder - create projects from templates

require ~/.fifth/lib/core.fs

\ Configuration
: templates-dir ( -- addr u ) s" templates/" ;
: output-dir    ( -- addr u ) s" output/" ;

\ Project state
256 constant name-len
create project-name name-len allot
create project-template name-len allot
variable project-name-len
variable project-template-len

\ --- Template Variables ---

: substitute ( template-addr template-u -- result-addr result-u )
  \ Replace {{NAME}} with project name
  \ TODO: Implement proper substitution
  ;

\ --- Directory Creation ---

: create-dir ( path-addr path-u -- )
  str-reset
  s" mkdir -p " str+
  str+
  str$ system drop ;

: create-file-from ( content-addr content-u path-addr path-u -- )
  w/o create-file throw >r
  r@ write-file throw
  r> close-file throw ;

\ --- Template: Web App ---

: scaffold-webapp ( name-addr name-u -- )
  s" Creating webapp: " type 2dup type cr

  \ Create directories
  str-reset output-dir str+ 2dup str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /src" str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /public" str+ str$ create-dir

  \ Create package.json
  str-reset output-dir str+ 2dup str+ s" /package.json" str+ str$
  s\" {\n  \"name\": \"" str-reset str+
  2swap 2dup 2>r str+
  s\" \",\n  \"version\": \"0.1.0\",\n  \"scripts\": {\n    \"start\": \"http-server public\"\n  }\n}" str+
  str$ 2swap create-file-from

  \ Create index.html
  str-reset output-dir str+ 2r@ str+ s" /public/index.html" str+ str$
  s" <!DOCTYPE html><html><head><title>" str-reset str+
  2r@ str+
  s\" </title></head><body><h1>Welcome to " str+
  2r@ str+
  s" </h1></body></html>" str+
  str$ 2swap create-file-from

  \ Create README
  str-reset output-dir str+ 2r> str+ s" /README.md" str+ str$
  s" # " str-reset str+
  project-name project-name-len @ str+
  s\" \n\nGenerated by Fifth project-scaffolder.\n" str+
  str$ 2swap create-file-from

  s" Webapp scaffolded successfully!" type cr ;

\ --- Template: CLI ---

: scaffold-cli ( name-addr name-u -- )
  s" Creating CLI app: " type 2dup type cr

  \ Create directories
  str-reset output-dir str+ 2dup str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /src" str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /tests" str+ str$ create-dir

  \ Create main file
  str-reset output-dir str+ 2dup str+ s" /src/main.fs" str+ str$
  s" \\ " str-reset str+ 2swap 2dup 2>r str+ s"  - CLI Application\n" str+
  s" \n\\ TODO: Implement your CLI here\n" str+
  s" \n: main  s\" Hello from " str+ 2r@ str+ s" !\" type cr ;\n" str+
  s" \nmain\nbye\n" str+
  str$ 2swap create-file-from

  2r> 2drop
  s" CLI scaffolded successfully!" type cr ;

\ --- Template: Library ---

: scaffold-library ( name-addr name-u -- )
  s" Creating library: " type 2dup type cr

  \ Create directories
  str-reset output-dir str+ 2dup str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /src" str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /tests" str+ str$ create-dir
  str-reset output-dir str+ 2dup str+ s" /docs" str+ str$ create-dir

  \ Create main library file
  str-reset output-dir str+ 2dup str+ s" /src/" str+ 2dup str+ s" .fs" str+ str$
  s" \\ " str-reset str+ 2swap 2dup 2>r str+ s"  - Library\n" str+
  s" \n\\ Public API\n" str+
  s" \n: " str+ 2r@ str+ s" -version  ( -- addr u ) s\" 0.1.0\" ;\n" str+
  str$ 2swap create-file-from

  2r> 2drop
  s" Library scaffolded successfully!" type cr ;

\ --- Main ---

: ensure-dirs ( -- )
  s" mkdir -p templates output" system drop ;

: list-templates ( -- )
  s" Available templates:" type cr
  s"   webapp   - Web application" type cr
  s"   cli      - Command-line tool" type cr
  s"   library  - Reusable library" type cr ;

: usage ( -- )
  s" Project Scaffolder" type cr
  s" " type cr
  s" Usage:" type cr
  s"   ./fifth project-scaffolder/main.fs <template> <name>" type cr
  s" " type cr
  list-templates ;

: main ( -- )
  ensure-dirs

  argc @ 3 < if
    usage exit
  then

  1 argv  \ template
  2dup s" webapp" compare 0= if
    2drop 2 argv scaffold-webapp exit
  then
  2dup s" cli" compare 0= if
    2drop 2 argv scaffold-cli exit
  then
  2dup s" library" compare 0= if
    2drop 2 argv scaffold-library exit
  then
  2drop

  s" Unknown template" type cr
  list-templates ;

main
bye
